version: "3"

networks:
    default:
        name: media

services:
    #vpn:
     #   image: ghcr.io/bubuntux/nordlynx:latest
      #  container_name: vpn
       # restart: unless-stopped
        #environment:
         #   - PRIVATE_KEY=aLVKCFqkRwDrmpc7NZISdLdtxZUrBzMCIoaTJpsnJl0=
        #ports:
         #   - 8080:8080
          #  - 6881:6881
           # - 6881:6881/udp
        #cap_add:
         #   - NET_ADMIN
          #  - NET_RAW
           # - SYS_MODULE
        #sysctls:
         #   - net.ipv4.conf.all.src_valid_mark=1

    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
        volumes:
            - /docker/jellyfin/config:/config
            - /mnt/m/anime:/anime
            - /mnt/m/Movies:/movies
        ports:
            - 8096:8096
        restart: unless-stopped

    jellyfin-cultured:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin-cultured
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
        volumes:
            - /docker/jellyfin-cultured/config:/config
            - /mnt/f/Hentai/Videos:/cultured-anime
        ports:
            - 8097:8096
        restart: unless-stopped

    stash:
        image: stashapp/stash:latest
        container_name: stash
        restart: unless-stopped
        environment:
            - STASH_STASH=/data
            - STASH_GENERATED=/generated
            - STASH_METADATA=/metadata
            - STASH_CACHE=/cache
            - STASH_PORT=9999
        volumes:
            - /docker/stash/config:/root/.stash
            - /docker/stash/generated:/generated
            - /docker/stash/metadata:/metadata
            - /docker/stash/cache:/cache
            - /docker/stash/scrapers:/root/.stash/scrapers
            - /etc/localtime:/etc/localtime:ro
            - /mnt/f/Porn/Videos/Regular:/data
            - /mnt/f/Porn/Videos/Playboy:/data2
        ports:
            - 9999:9999
        logging:
            driver: json-file
            options:
                max-file: "10"
                max-size: 2m

    #sonarr:
     #   image: lscr.io/linuxserver/sonarr:latest
      #  container_name: sonarr
       # restart: unless-stopped
        #environment:
         #   - PUID=1000
          #  - PGID=1000
           # - TZ=America/New_York
        #volumes:
         #   - /docker/sonarr/config:/config
          #  - /mnt/m/torrents:/data/torrents
           # - /mnt/m/anime:/data/media/anime
        #ports:
         #   - 8989:8989

    #prowlarr:
     #   image: lscr.io/linuxserver/prowlarr:develop
      #  container_name: prowlarr
       # restart: unless-stopped
        #environment:
         #   - PUID=1000
          #  - PGID=1000
           # - TZ=America/New_York
        #volumes:
         #   - /docker/prowlarr/config:/config
        #ports:
         #   - 9696:9696

    #torrent:
     #   image: lscr.io/linuxserver/qbittorrent:latest
      #  container_name: torrent
       # restart: unless-stopped
        #environment:
         #   - PUID=1000
          #  - PGID=1000
           # - TZ=America/New_York
            #- WEBUI_PORT=8080
        #volumes:
         #   - /docker/qbittorrent/config:/config
          #  - /docker/qbittorrent/nightwalker:/opt/nightwalker
           # - /mnt/m/torrents:/data/torrents
        #network_mode: service:vpn
        #depends_on:
         #   - vpn

    stash-chromium:
        image: chromedp/headless-shell:latest
        container_name: stash-chromium
        restart: unless-stopped
        ports:
            - 9222:9222